"""added event poster file id field

Revision ID: 11734a7291a7
Revises: 7285513e270d
Create Date: 2025-12-14 23:53:45.866787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '11734a7291a7'
down_revision: Union[str, Sequence[str], None] = '7285513e270d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_events', sa.Column('event_poster_file_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.alter_column('tbl_events', 'event_poster_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tbl_events', 'event_poster_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('tbl_events', 'event_poster_file_id')
    # ### end Alembic commands ###
