"""added ticket/event relationship

Revision ID: 181b03eae5f3
Revises: 8546d01d4b69
Create Date: 2025-11-30 20:43:58.679391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '181b03eae5f3'
down_revision: Union[str, Sequence[str], None] = '8546d01d4b69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_tickets', sa.Column('event_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'tbl_tickets', 'tbl_events', ['event_id'], ['event_uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_tickets', type_='foreignkey')
    op.drop_column('tbl_tickets', 'event_id')
    # ### end Alembic commands ###
