"""made poster_file_id none by default

Revision ID: 5cf9dd44c9dd
Revises: 11734a7291a7
Create Date: 2025-12-14 23:59:31.885777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5cf9dd44c9dd'
down_revision: Union[str, Sequence[str], None] = '11734a7291a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tbl_events', 'event_poster_file_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tbl_events', 'event_poster_file_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
