"""init

Revision ID: 67e26377ed9e
Revises: 
Create Date: 2025-11-20 09:18:19.282988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '67e26377ed9e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_events',
    sa.Column('event_uid', sa.Uuid(), nullable=False),
    sa.Column('event_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('event_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_location_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('event_capacity', sa.Integer(), nullable=False),
    sa.Column('event_status', sa.Enum('ACTIVE', 'INACTIVE', name='eventstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('event_uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_events')
    # ### end Alembic commands ###
