"""add the ticket entity

Revision ID: 8546d01d4b69
Revises: 6b1476818992
Create Date: 2025-11-30 20:01:54.843297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8546d01d4b69'
down_revision: Union[str, Sequence[str], None] = '6b1476818992'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_tickets',
    sa.Column('ticket_uid', sa.Uuid(), nullable=False),
    sa.Column('ticket_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ticket_status', sa.Enum('USED', 'UNUSED', name='ticketstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('ticket_uid')
    )
    op.create_index(op.f('ix_tbl_tickets_ticket_code'), 'tbl_tickets', ['ticket_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_tickets_ticket_code'), table_name='tbl_tickets')
    op.drop_table('tbl_tickets')
    # ### end Alembic commands ###
