"""took out the status from the event model

Revision ID: 98821bc52e79
Revises: 67e26377ed9e
Create Date: 2025-11-20 17:25:15.605586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98821bc52e79'
down_revision: Union[str, Sequence[str], None] = '67e26377ed9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_events', 'event_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_events', sa.Column('event_status', postgresql.ENUM('ACTIVE', 'INACTIVE', name='eventstatus'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
