"""added scanned at field to ticket

Revision ID: ca4780a29a8e
Revises: 181b03eae5f3
Create Date: 2025-11-30 22:11:44.093032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ca4780a29a8e'
down_revision: Union[str, Sequence[str], None] = '181b03eae5f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_tickets', sa.Column('scanned_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_tickets', 'scanned_at')
    # ### end Alembic commands ###
