"""added event_tag to event model

Revision ID: cca09d036a0a
Revises: ea5b611ece8b
Create Date: 2025-12-04 20:34:22.670102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cca09d036a0a'
down_revision: Union[str, Sequence[str], None] = 'ea5b611ece8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_events', sa.Column('event_tag', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_events', 'event_tag')
    # ### end Alembic commands ###
