"""added longitude and latitude to event model

Revision ID: ea5b611ece8b
Revises: d3c5bf0d642e
Create Date: 2025-12-04 16:58:36.255316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ea5b611ece8b'
down_revision: Union[str, Sequence[str], None] = 'd3c5bf0d642e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_events', sa.Column('event_longitude', sa.Float(), nullable=True))
    op.add_column('tbl_events', sa.Column('event_latitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_events', 'event_latitude')
    op.drop_column('tbl_events', 'event_longitude')
    # ### end Alembic commands ###
